services:
  mongodb:
    image: mongo
    ports: 
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin 
      MONGO_INITDB_ROOT_PASSWORD: adminpass
    volumes:
      - mongodb_volume:/data/db
  streamlit_data_app:
    image: streamlit_data_app
    ports:
      - 8501:8501

volumes:
  mongodb_volume: